# Generated by Django 5.2 on 2026-04-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField()),
                ('lloc', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('imatge', models.ImageField(upload_to='expos')),
                ('estat', models.CharField(choices=[('INIT', 'Inici'), ('DISPONIBLE', 'Disponible'), ('ACTUALITZABLE', 'Actualitzable')], default='INIT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('imatge', models.ImageField(upload_to='items')),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Uxiapp.expo')),
            ],
        ),
        migrations.CreateModel(
            name='Intents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(upload_to='intents')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Uxiapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(upload_to='imatges')),
                ('es_publica', models.BooleanField(default=True)),
                ('es_destacada', models.BooleanField(default=False, help_text='Marcar  perquè sigui la imatge de portada o destacada')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Uxiapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='Uxiapp.etiqueta')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='Uxiapp.item')),
            ],
        ),
    ]
