# Generated by Django 5.2 on 2026-04-28 15:49

import Uxiapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('pare', models.ForeignKey(blank=True, help_text='Deixa en blanc si és una etiqueta arrel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filles', to='Uxiapp.etiqueta', verbose_name='Etiqueta pare')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Expo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('data_inici', models.DateField(verbose_name="Data d'inici")),
                ('data_fi', models.DateField(verbose_name='Data de fi')),
                ('lloc', models.CharField(max_length=100, verbose_name='Lloc')),
                ('descripcio', models.TextField(verbose_name='Descripció')),
                ('imatge', models.ImageField(upload_to=Uxiapp.models.expo_upload, verbose_name='Imatge')),
                ('estat', models.CharField(choices=[('INIT', 'Inici'), ('DISPONIBLE', 'Disponible'), ('ACTUALITZABLE', 'Actualitzable')], default='INIT', max_length=20, verbose_name='Estat')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('propietari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expos', to=settings.AUTH_USER_MODEL, verbose_name='Propietari')),
            ],
            options={
                'verbose_name': 'Exposició',
                'verbose_name_plural': 'Exposicions',
                'ordering': ['-data_inici'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('descripcio', models.TextField(verbose_name='Descripció')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('etiquetes', models.ManyToManyField(blank=True, related_name='items', to='Uxiapp.etiqueta', verbose_name='Etiquetes')),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Uxiapp.expo', verbose_name='Exposició')),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítems',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(upload_to=Uxiapp.models.intent_upload, verbose_name='Foto enviada')),
                ('encert', models.BooleanField(blank=True, help_text='True=identificat correctament, False=incorrecte, Null=pendent de validar', null=True, verbose_name='Encert')),
                ('confiança', models.FloatField(blank=True, help_text='Percentatge de confiança retornat pel model (0.0 – 1.0)', null=True, verbose_name='Confiança IA')),
                ('descripcio_ia', models.TextField(blank=True, null=True, verbose_name='Descripció IA')),
                ('etiquetes_ia', models.JSONField(blank=True, null=True, verbose_name='Etiquetes IA')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='Uxiapp.item', verbose_name='Ítem identificat')),
            ],
            options={
                'verbose_name': 'Intent',
                'verbose_name_plural': 'Intents',
                'ordering': ['-creat_el'],
            },
        ),
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(upload_to=Uxiapp.models.imatge_upload, verbose_name="Arxiu d'imatge")),
                ('es_publica', models.BooleanField(default=True, help_text='Pública: apta pel frontend.', verbose_name='Pública')),
                ('es_destacada', models.BooleanField(default=False, help_text='Marcar perquè sigui la imatge de portada o destacada', verbose_name='Destacada')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imatges', to='Uxiapp.item', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Imatge',
                'verbose_name_plural': 'Imatges',
                'ordering': ['ordre', 'creat_el'],
            },
        ),
    ]
