# Generated by Django 5.2 on 2026-04-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel1',
            name='nombre_coche',
            field=models.CharField(default='desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
