# Generated by Django 5.2 on 2026-04-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imatge',
        ),
        migrations.RemoveField(
            model_name='item',
            name='imatge_destacada',
        ),
    ]
