# Generated by Django 5.2 on 2026-04-28 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariAnonim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(max_length=100, unique=True, verbose_name='ID de cookie')),
                ('data_creacio', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
                ('ultima_activitat', models.DateTimeField(auto_now=True, verbose_name='Última activitat')),
            ],
            options={
                'verbose_name': 'Usuari anònim',
                'verbose_name_plural': 'Usuaris anònims',
                'ordering': ['-ultima_activitat'],
            },
        ),
        migrations.AddField(
            model_name='intent',
            name='usuari_anonim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='Uxiapp.usuarianonim', verbose_name='Usuari anònim'),
        ),
    ]
