# Generated by Django 5.2 on 2026-04-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0002_mymodel1_nombre_coche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etiqueta', models.CharField(max_length=100)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='Uxiapp.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Expo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_expo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='expos')),
            ],
        ),
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(upload_to='imatges')),
            ],
        ),
        migrations.CreateModel(
            name='Intents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge_intent', models.ImageField(upload_to='intents')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(max_length=100)),
                ('descripcion_item', models.TextField()),
                ('imagen_item', models.ImageField(upload_to='items')),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uxiapp.expo')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel1',
        ),
        migrations.AddField(
            model_name='intents',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uxiapp.item'),
        ),
        migrations.AddField(
            model_name='imatge',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uxiapp.item'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uxiapp.item'),
        ),
    ]
