# Generated by Django 5.2 on 2026-05-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0002_usuarianonim_intent_usuari_anonim'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='idioma',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Castellà'), ('en', 'Anglès'), ('fr', 'Francès')], default='ca', help_text="Idioma per a la pronunciació de l'identificador de l'ítem (TTS)", max_length=2, verbose_name='Idioma'),
        ),
    ]
