# Generated by Django 5.2 on 2026-05-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0002_usuarianonim_intent_usuari_anonim'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='train_status',
            field=models.CharField(choices=[('IDLE', 'Inactiu'), ('QUEUED', 'En cua'), ('RUNNING', 'Entrenant'), ('OK', 'Completat'), ('ERROR', 'Error'), ('CANCELLED', 'Cancel·lat'), ('REPLACE', 'Reemplaçant')], default='IDLE', max_length=20, verbose_name='Estat entrenament IA'),
        ),
    ]
