# Generated by Django 5.2 on 2026-04-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0002_remove_item_imatge_remove_item_imatge_destacada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='Uxiapp.item', verbose_name='Ítem identificat'),
        ),
    ]
