# Generated by Django 5.2 on 2026-04-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0003_alter_intent_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='descripcio_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Descripció IA'),
        ),
        migrations.AddField(
            model_name='intent',
            name='etiquetes_ia',
            field=models.JSONField(blank=True, null=True, verbose_name='Etiquetes IA'),
        ),
    ]
