# Generated by Django 5.2 on 2026-04-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0003_etiqueta_expo_imatge_intents_item_delete_mymodel1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='nombre_etiqueta',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='expo',
            old_name='nombre_expo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='imatge',
            old_name='imatge',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='intents',
            old_name='imatge_intent',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descripcion_item',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='imagen_item',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nombre_item',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='Uxiapp.item'),
        ),
        migrations.AlterField(
            model_name='imatge',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Uxiapp.item'),
        ),
        migrations.AlterField(
            model_name='intents',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Uxiapp.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Uxiapp.expo'),
        ),
    ]
