# Generated by Django 5.2 on 2026-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0004_rename_nombre_etiqueta_etiqueta_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='estado',
            field=models.CharField(choices=[('INIT', 'Init'), ('DISPONIBLE', 'Disponible'), ('ACTUALITZABLE', 'Actualitzable')], default='INIT', max_length=20),
        ),
        migrations.AddField(
            model_name='imatge',
            name='es_publica',
            field=models.BooleanField(default=True),
        ),
    ]
