# Generated by Django 5.2 on 2026-04-28 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0004_intent_descripcio_ia_intent_etiquetes_ia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='propietari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expos', to=settings.AUTH_USER_MODEL, verbose_name='Propietari'),
        ),
    ]
