# Generated by Django 5.2 on 2026-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0005_expo_estado_imatge_es_publica'),
    ]

    operations = [
        migrations.AddField(
            model_name='imatge',
            name='es_destacada',
            field=models.BooleanField(default=False, help_text='Marcar  para que sea la imagen de portada o destacada'),
        ),
    ]
