# Generated by Django 5.2 on 2026-04-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uxiapp', '0006_imatge_es_destacada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagen',
        ),
    ]
